name: Bundle CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'bundle.yml'
      - '.github/workflows/bundle-ci.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          echo "$HOME/.databricks/cli/bin" >> $GITHUB_PATH
      
      - name: Lint Python notebooks
        run: |
          pip install ruff
          ruff check src/notebooks/
      
      - name: Run unit tests
        run: |
          pip install pytest pytest-cov
          # Placeholder for actual tests
          echo "Unit tests would run here"
      
      - name: Validate Databricks Asset Bundle
        env:
          DATABRICKS_HOST: https://adb-1591171967825930.10.azuredatabricks.net
          DATABRICKS_TOKEN: ${{ secrets.DBX_TOKEN }}
        run: |
          databricks bundle validate