name: Bundle CD - Dev

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'bundle.yml'
      - 'iac/**'
      - '.github/workflows/bundle-cd-dev.yml'

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          echo "$HOME/.databricks/cli/bin" >> $GITHUB_PATH
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.ARM_CLIENT_ID }}",
              "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.ARM_TENANT_ID }}"
            }
      
      - name: Deploy to Dev
        env:
          DATABRICKS_HOST: https://adb-1591171967825930.10.azuredatabricks.net
          DATABRICKS_AUTH_TYPE: azure-cli
        run: |
          databricks bundle deploy --target dev
      
      - name: Run ELT Pipeline
        env:
          DATABRICKS_HOST: https://adb-1591171967825930.10.azuredatabricks.net
          DATABRICKS_AUTH_TYPE: azure-cli
        run: |
          # Get job ID and start the ELT pipeline
          JOB_ID=$(databricks jobs list --output json | jq -r '.[] | select(.settings.name | contains("ELT Demo Pipeline")) | .job_id')
          echo "Starting job ID: $JOB_ID"
          RUN_ID=$(databricks jobs run-now $JOB_ID --no-wait --output json | jq -r '.run_id')
          echo "Job run started with ID: $RUN_ID"
          
          # Wait for completion with timeout
          databricks jobs run-now $JOB_ID --timeout 20m